package proyecto_recursoshumanos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frm_Mantempleadocapacitacion extends javax.swing.JFrame {
    
private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(
                frm_Mantempleadocapacitacion.class.getName());

private Connection cn;

public frm_Mantempleadocapacitacion() {

    initComponents();

    setLocationRelativeTo(null);

    // CONEXIÓN A MYSQL
    Conexion_bd_Luis conexionBD =
            new Conexion_bd_Luis();

    cn = conexionBD.conectar();

    // BOTONES DESACTIVADOS AL INICIAR
    BTN_Guardar.setEnabled(false);
    BTN_Modificar.setEnabled(false);
    BTN_Desactivar.setEnabled(false);

    // TABLA VACÍA AL INICIAR
    DefaultTableModel modelo =
            (DefaultTableModel)
            JTABLE_Mantempleadocapacitacion.getModel();

    modelo.setRowCount(0);
}

private void limpiarCampos() {

    txtidempleadocapacitacion.setText("");
    txtidcapacitacion.setText("");
    txtidempleado.setText("");
    txtidestadoaprobacion.setText("");
    txtnotaobtenida.setText("");
    txttienecertificado.setText("");

    JTABLE_Mantempleadocapacitacion.clearSelection();
}

private void cargarTabla() {

    DefaultTableModel modelo =
            (DefaultTableModel)
            JTABLE_Mantempleadocapacitacion.getModel();

    modelo.setRowCount(0);

    String sql =
            "SELECT id_empleado_capacitacion, "
            + "id_capacitacion, "
            + "id_empleado, "
            + "estado_aprobacion, "
            + "nota_obtenida, "
            + "tiene_certificado "
            + "FROM empleado_capacitacion "
            + "ORDER BY id_empleado_capacitacion";

    try {

        if (cn == null || cn.isClosed()) {

            Conexion_bd_Luis conexionBD =
                    new Conexion_bd_Luis();

            cn = conexionBD.conectar();
        }

        try (PreparedStatement ps = cn.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {

                modelo.addRow(new Object[]{

                    rs.getInt("id_empleado_capacitacion"),

                    rs.getInt("id_capacitacion"),

                    rs.getInt("id_empleado"),

                    rs.getString("estado_aprobacion"),

                    rs.getBigDecimal("nota_obtenida"),

                    rs.getString("tiene_certificado")
                });
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al cargar empleados capacitación:\n"
                + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidempleadocapacitacion = new javax.swing.JTextField();
        BTN_verempleadocapacitacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidcapacitacion = new javax.swing.JTextField();
        txtnotaobtenida = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtidempleado = new javax.swing.JTextField();
        txttienecertificado = new javax.swing.JTextField();
        txtidestadoaprobacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        BTN_Desactivar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_Buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mantempleadocapacitacion = new javax.swing.JTable();
        BTN_PDF = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        BTN_Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id Empleado Capacitacion:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tiene Certificado:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtidempleadocapacitacion.setEditable(false);
        txtidempleadocapacitacion.setBackground(new java.awt.Color(255, 255, 255));
        txtidempleadocapacitacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidempleadocapacitacion.setForeground(new java.awt.Color(0, 0, 204));
        txtidempleadocapacitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidempleadocapacitacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtidempleadocapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 370, 30));

        BTN_verempleadocapacitacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_verempleadocapacitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        BTN_verempleadocapacitacion.setText("VER EMPLEADO");
        BTN_verempleadocapacitacion.setActionCommand("VER Permiso Licencia");
        BTN_verempleadocapacitacion.addActionListener(this::BTN_verempleadocapacitacionActionPerformed);
        jPanel2.add(BTN_verempleadocapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 280, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Id Capacitacion:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Estado Aprobacion:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Nota Obtenida:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtidcapacitacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidcapacitacion.setForeground(new java.awt.Color(0, 0, 204));
        txtidcapacitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidcapacitacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidcapacitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidcapacitacionKeyTyped(evt);
            }
        });
        jPanel2.add(txtidcapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 370, 30));

        txtnotaobtenida.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnotaobtenida.setForeground(new java.awt.Color(0, 0, 204));
        txtnotaobtenida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnotaobtenida.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnotaobtenida.addActionListener(this::txtnotaobtenidaActionPerformed);
        txtnotaobtenida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnotaobtenidaKeyTyped(evt);
            }
        });
        jPanel2.add(txtnotaobtenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 370, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Id Empleado");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtidempleado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidempleado.setForeground(new java.awt.Color(0, 0, 204));
        txtidempleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidempleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidempleado.addActionListener(this::txtidempleadoActionPerformed);
        txtidempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyTyped(evt);
            }
        });
        jPanel2.add(txtidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 370, 30));

        txttienecertificado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txttienecertificado.setForeground(new java.awt.Color(0, 0, 204));
        txttienecertificado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttienecertificado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttienecertificado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttienecertificadoKeyTyped(evt);
            }
        });
        jPanel2.add(txttienecertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 370, 30));

        txtidestadoaprobacion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidestadoaprobacion.setForeground(new java.awt.Color(0, 0, 204));
        txtidestadoaprobacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidestadoaprobacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidestadoaprobacion.addActionListener(this::txtidestadoaprobacionActionPerformed);
        txtidestadoaprobacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidestadoaprobacionKeyTyped(evt);
            }
        });
        jPanel2.add(txtidestadoaprobacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 370, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("EMPLEADO CAPACITACION");

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuevo.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Guardar.png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modificar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);

        BTN_Desactivar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/serv.png"))); // NOI18N
        BTN_Desactivar.setText("DAR DE BAJA");
        BTN_Desactivar.addActionListener(this::BTN_DesactivarActionPerformed);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar Empleado:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, 30));

        TXT_Buscar.addActionListener(this::TXT_BuscarActionPerformed);
        TXT_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyTyped(evt);
            }
        });
        jPanel3.add(TXT_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BUSCAR");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        JTABLE_Mantempleadocapacitacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mantempleadocapacitacion.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mantempleadocapacitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Empleado Capacitacion", "Id Capacitacion", "Id Empleado", "Estado Aprobacion", "Nota Obtenida", "Tiene Certificado"
            }
        ));
        JTABLE_Mantempleadocapacitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_MantempleadocapacitacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mantempleadocapacitacion);

        BTN_PDF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);

        BTN_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salir.png"))); // NOI18N
        BTN_Cerrar.setText("Cerrar");
        BTN_Cerrar.addActionListener(this::BTN_CerrarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BTN_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTN_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BTN_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(BTN_Desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(BTN_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(BTN_EXCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(BTN_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Desactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_EXCEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_verempleadocapacitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_verempleadocapacitacionActionPerformed
        cargarTabla();
    }//GEN-LAST:event_BTN_verempleadocapacitacionActionPerformed

    private void txtidcapacitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidcapacitacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidcapacitacionKeyTyped

    private void txtnotaobtenidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotaobtenidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotaobtenidaActionPerformed

    private void txtnotaobtenidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnotaobtenidaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotaobtenidaKeyTyped

    private void txtidempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoActionPerformed

    private void txtidempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoKeyTyped

    private void txttienecertificadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttienecertificadoKeyTyped

    }//GEN-LAST:event_txttienecertificadoKeyTyped

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
    limpiarCampos();

    BTN_Guardar.setEnabled(true);
    BTN_Modificar.setEnabled(false);
    BTN_Desactivar.setEnabled(false);

    txtidcapacitacion.requestFocus();
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
    if (txtidcapacitacion.getText().trim().isEmpty()
            || txtidempleado.getText().trim().isEmpty()
            || txtidestadoaprobacion.getText().trim().isEmpty()
            || txtnotaobtenida.getText().trim().isEmpty()
            || txttienecertificado.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Complete todos los campos."
        );

        return;
    }

    String sql =
            "INSERT INTO empleado_capacitacion "
            + "(id_capacitacion, "
            + "id_empleado, "
            + "estado_aprobacion, "
            + "nota_obtenida, "
            + "tiene_certificado) "
            + "VALUES (?, ?, ?, ?, ?)";

    try (PreparedStatement ps =
            cn.prepareStatement(sql)) {

        ps.setInt(
                1,
                Integer.parseInt(
                        txtidcapacitacion
                                .getText()
                                .trim()
                )
        );

        ps.setInt(
                2,
                Integer.parseInt(
                        txtidempleado
                                .getText()
                                .trim()
                )
        );

        ps.setInt(
                3,
                Integer.parseInt(
                        txtidestadoaprobacion
                                .getText()
                                .trim()
                )
        );

        ps.setBigDecimal(
                4,
                new java.math.BigDecimal(
                        txtnotaobtenida
                                .getText()
                                .trim()
                )
        );

        ps.setString(
                5,
                txttienecertificado
                        .getText()
                        .trim()
        );

        ps.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Empleado capacitación registrado correctamente."
        );

        limpiarCampos();

        BTN_Guardar.setEnabled(false);

        cargarTabla();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Los IDs y la nota deben tener un formato válido."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al guardar:\n"
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
    if (txtidempleadocapacitacion
            .getText()
            .trim()
            .isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un registro de la tabla."
        );

        return;
    }

    if (txtidcapacitacion.getText().trim().isEmpty()
            || txtidempleado.getText().trim().isEmpty()
            || txtidestadoaprobacion.getText().trim().isEmpty()
            || txtnotaobtenida.getText().trim().isEmpty()
            || txttienecertificado.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Complete todos los campos."
        );

        return;
    }

    String sql =
            "UPDATE empleado_capacitacion SET "
            + "id_capacitacion = ?, "
            + "id_empleado = ?, "
            + "id_estado_aprobacion = ?, "
            + "nota_obtenida = ?, "
            + "tiene_certificado = ? "
            + "WHERE id_empleado_capacitacion = ?";

    try (PreparedStatement ps =
            cn.prepareStatement(sql)) {

        ps.setInt(
                1,
                Integer.parseInt(
                        txtidcapacitacion
                                .getText()
                                .trim()
                )
        );

        ps.setInt(
                2,
                Integer.parseInt(
                        txtidempleado
                                .getText()
                                .trim()
                )
        );

        ps.setInt(
                3,
                Integer.parseInt(
                        txtidestadoaprobacion
                                .getText()
                                .trim()
                )
        );

        ps.setBigDecimal(
                4,
                new java.math.BigDecimal(
                        txtnotaobtenida
                                .getText()
                                .trim()
                )
        );

        ps.setString(
                5,
                txttienecertificado
                        .getText()
                        .trim()
        );

        ps.setInt(
                6,
                Integer.parseInt(
                        txtidempleadocapacitacion
                                .getText()
                                .trim()
                )
        );

        ps.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Registro modificado correctamente."
        );

        limpiarCampos();

        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        cargarTabla();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Los datos numéricos no tienen un formato válido."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al modificar:\n"
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_DesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DesactivarActionPerformed
    if (txtidempleadocapacitacion
            .getText()
            .trim()
            .isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un registro."
        );

        return;
    }

    String sql =
            "UPDATE empleado_capacitacion "
            + "SET estado = 'INACTIVO' "
            + "WHERE id_empleado_capacitacion = ?";

    try (PreparedStatement ps =
            cn.prepareStatement(sql)) {

        ps.setInt(
                1,
                Integer.parseInt(
                        txtidempleadocapacitacion
                                .getText()
                                .trim()
                )
        );

        ps.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Registro dado de baja correctamente."
        );

        limpiarCampos();

        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        cargarTabla();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al dar de baja:\n"
                + e.getMessage()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "El ID debe ser numérico."
        );
    }
    }//GEN-LAST:event_BTN_DesactivarActionPerformed

    private void TXT_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyReleased
    String buscar =
            TXT_Buscar.getText().trim();

    DefaultTableModel modelo =
            (DefaultTableModel)
            JTABLE_Mantempleadocapacitacion.getModel();

    modelo.setRowCount(0);

    String sql =
            "SELECT id_empleado_capacitacion, "
            + "id_capacitacion, "
            + "id_empleado, "
            + "id_estado_aprobacion, "
            + "nota_obtenida, "
            + "tiene_certificado "
            + "FROM empleado_capacitacion "
            + "WHERE CAST(id_empleado_capacitacion AS CHAR) LIKE ? "
            + "ORDER BY id_empleado_capacitacion";

    try (PreparedStatement ps =
            cn.prepareStatement(sql)) {

        ps.setString(
                1,
                "%" + buscar + "%"
        );

        try (ResultSet rs =
                ps.executeQuery()) {

            while (rs.next()) {

                modelo.addRow(new Object[]{

                    rs.getInt(
                            "id_empleado_capacitacion"),

                    rs.getInt(
                            "id_capacitacion"),

                    rs.getInt(
                            "id_empleado"),

                    rs.getInt(
                            "id_estado_aprobacion"),

                    rs.getBigDecimal(
                            "nota_obtenida"),

                    rs.getString(
                            "tiene_certificado")
                });
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al buscar:\n"
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_TXT_BuscarKeyReleased

    private void TXT_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyTyped

    }//GEN-LAST:event_TXT_BuscarKeyTyped

    private void JTABLE_MantempleadocapacitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_MantempleadocapacitacionMouseClicked
    int fila =
            JTABLE_Mantempleadocapacitacion
                    .getSelectedRow();

    if (fila >= 0) {

        // ID EMPLEADO CAPACITACION
        txtidempleadocapacitacion.setText(
                JTABLE_Mantempleadocapacitacion
                        .getValueAt(fila, 0)
                        .toString()
        );

        // ID CAPACITACION
        txtidcapacitacion.setText(
                JTABLE_Mantempleadocapacitacion
                        .getValueAt(fila, 1)
                        .toString()
        );

        // ID EMPLEADO
        txtidempleado.setText(
                JTABLE_Mantempleadocapacitacion
                        .getValueAt(fila, 2)
                        .toString()
        );

        // ESTADO APROBACION
        txtidestadoaprobacion.setText(
                JTABLE_Mantempleadocapacitacion
                        .getValueAt(fila, 3)
                        .toString()
        );

        // NOTA OBTENIDA
        txtnotaobtenida.setText(
                JTABLE_Mantempleadocapacitacion
                        .getValueAt(fila, 4)
                        .toString()
        );

        // TIENE CERTIFICADO
        Object certificado =
                JTABLE_Mantempleadocapacitacion
                        .getValueAt(fila, 5);

        if (certificado != null) {

            txttienecertificado.setText(
                    certificado.toString()
            );

        } else {

            txttienecertificado.setText("");
        }

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(true);
        BTN_Desactivar.setEnabled(true);
    }
    }//GEN-LAST:event_JTABLE_MantempleadocapacitacionMouseClicked

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void BTN_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BTN_CerrarActionPerformed

    private void txtidestadoaprobacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidestadoaprobacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidestadoaprobacionActionPerformed

    private void txtidestadoaprobacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidestadoaprobacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidestadoaprobacionKeyTyped

    private void TXT_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_Mantempleadocapacitacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar;
    private javax.swing.JButton BTN_Desactivar;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_verempleadocapacitacion;
    private javax.swing.JTable JTABLE_Mantempleadocapacitacion;
    private javax.swing.JTextField TXT_Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtidcapacitacion;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtidempleadocapacitacion;
    private javax.swing.JTextField txtidestadoaprobacion;
    private javax.swing.JTextField txtnotaobtenida;
    private javax.swing.JTextField txttienecertificado;
    // End of variables declaration//GEN-END:variables
}
