package proyecto_recursoshumanos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_Mantcontrato extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_Mantcontrato.class.getName());
    private Connection cn;

    public frm_Mantcontrato() {
        initComponents();

        Conexion_bd_Luis conexionBD = new Conexion_bd_Luis();
        cn = conexionBD.conectar();

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        limpiarCampos();

        DefaultTableModel modelo = (DefaultTableModel) JTABLE_Mantcontrato.getModel();
        modelo.setRowCount(0);
    }
private void limpiarCampos() {

    txtidcontrato.setText("");
    txtidempleado.setText("");
    txtidtipocontrato.setText("");
    txtidcargo.setText("");
    txtidsede.setText("");
    txtidmodalidad.setText("");
    txtiddepartamentoacademico.setText("");
    txtsalario.setText("");
    txthorassemanales.setText("");
    txtasignacionfamiliar.setText("");
    txtdetalles.setText("");
    txtobservaciones.setText("");
    txtestado.setText("");

    jDatefechainicio.setDate(null);
    jDatefechafin.setDate(null);
}
private void cargarTabla() {

    DefaultTableModel modelo =
            (DefaultTableModel) JTABLE_Mantcontrato.getModel();

    modelo.setRowCount(0);

    String sql = "SELECT "
            + "id_contrato, "
            + "id_empleado, "
            + "id_tipo_contrato, "
            + "id_cargo, "
            + "id_sede, "
            + "id_modalidad, "
            + "id_departamento_academico, "
            + "salario, "
            + "horas_semanales, "
            + "asignacion_familiar, "
            + "fecha_inicio, "
            + "fecha_fin, "
            + "detalles, "
            + "observaciones, "
            + "estado "
            + "FROM contrato "
            + "ORDER BY id_contrato";

    try (PreparedStatement ps = cn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {

            modelo.addRow(new Object[]{
                rs.getInt("id_contrato"),
                rs.getInt("id_empleado"),
                rs.getInt("id_tipo_contrato"),
                rs.getInt("id_cargo"),
                rs.getInt("id_sede"),
                rs.getInt("id_modalidad"),
                rs.getInt("id_departamento_academico"),
                rs.getBigDecimal("salario"),
                rs.getInt("horas_semanales"),
                rs.getBigDecimal("asignacion_familiar"),
                rs.getDate("fecha_inicio"),
                rs.getDate("fecha_fin"),
                rs.getString("detalles"),
                rs.getString("observaciones"),
                rs.getString("estado")
            });
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al cargar contratos: " + e.getMessage()
        );
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidcontrato = new javax.swing.JTextField();
        BTN_vercontrato = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidempleado = new javax.swing.JTextField();
        txtidsede = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtidtipocontrato = new javax.swing.JTextField();
        txtidmodalidad = new javax.swing.JTextField();
        txtidcargo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtiddepartamentoacademico = new javax.swing.JTextField();
        txtsalario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txthorassemanales = new javax.swing.JTextField();
        txtasignacionfamiliar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtdetalles = new javax.swing.JTextField();
        txtobservaciones = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtestado = new javax.swing.JTextField();
        jDatefechafin = new com.toedter.calendar.JDateChooser();
        jDatefechainicio = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_Buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mantcontrato = new javax.swing.JTable();
        BTN_Desactivar = new javax.swing.JButton();
        BTN_PDF = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        BTN_Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id Contrato:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Id Modalidad:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtidcontrato.setEditable(false);
        txtidcontrato.setBackground(new java.awt.Color(255, 255, 255));
        txtidcontrato.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidcontrato.setForeground(new java.awt.Color(0, 0, 204));
        txtidcontrato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidcontrato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtidcontrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 370, 30));

        BTN_vercontrato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_vercontrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        BTN_vercontrato.setText("VER CONTRATO");
        BTN_vercontrato.setActionCommand("VER Permiso Licencia");
        BTN_vercontrato.addActionListener(this::BTN_vercontratoActionPerformed);
        jPanel2.add(BTN_vercontrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 280, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Id Empleado:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Id Cargo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Id Sede:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtidempleado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidempleado.setForeground(new java.awt.Color(0, 0, 204));
        txtidempleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidempleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyTyped(evt);
            }
        });
        jPanel2.add(txtidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 370, 30));

        txtidsede.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidsede.setForeground(new java.awt.Color(0, 0, 204));
        txtidsede.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidsede.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidsede.addActionListener(this::txtidsedeActionPerformed);
        txtidsede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidsedeKeyTyped(evt);
            }
        });
        jPanel2.add(txtidsede, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 370, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Id Tipo Contrato:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtidtipocontrato.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidtipocontrato.setForeground(new java.awt.Color(0, 0, 204));
        txtidtipocontrato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidtipocontrato.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidtipocontrato.addActionListener(this::txtidtipocontratoActionPerformed);
        txtidtipocontrato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidtipocontratoKeyTyped(evt);
            }
        });
        jPanel2.add(txtidtipocontrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 370, 30));

        txtidmodalidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidmodalidad.setForeground(new java.awt.Color(0, 0, 204));
        txtidmodalidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidmodalidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidmodalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidmodalidadKeyTyped(evt);
            }
        });
        jPanel2.add(txtidmodalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 370, 30));

        txtidcargo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidcargo.setForeground(new java.awt.Color(0, 0, 204));
        txtidcargo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidcargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidcargo.addActionListener(this::txtidcargoActionPerformed);
        txtidcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidcargoKeyTyped(evt);
            }
        });
        jPanel2.add(txtidcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 370, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Id Departamento Academico:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtiddepartamentoacademico.setEditable(false);
        txtiddepartamentoacademico.setBackground(new java.awt.Color(255, 255, 255));
        txtiddepartamentoacademico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtiddepartamentoacademico.setForeground(new java.awt.Color(0, 0, 204));
        txtiddepartamentoacademico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtiddepartamentoacademico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtiddepartamentoacademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 370, 30));

        txtsalario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtsalario.setForeground(new java.awt.Color(0, 0, 204));
        txtsalario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsalario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtsalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalarioKeyTyped(evt);
            }
        });
        jPanel2.add(txtsalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 370, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Salario:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Horas Semanales:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        txthorassemanales.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txthorassemanales.setForeground(new java.awt.Color(0, 0, 204));
        txthorassemanales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthorassemanales.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txthorassemanales.addActionListener(this::txthorassemanalesActionPerformed);
        txthorassemanales.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthorassemanalesKeyTyped(evt);
            }
        });
        jPanel2.add(txthorassemanales, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 370, 30));

        txtasignacionfamiliar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtasignacionfamiliar.setForeground(new java.awt.Color(0, 0, 204));
        txtasignacionfamiliar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtasignacionfamiliar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtasignacionfamiliar.addActionListener(this::txtasignacionfamiliarActionPerformed);
        txtasignacionfamiliar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtasignacionfamiliarKeyTyped(evt);
            }
        });
        jPanel2.add(txtasignacionfamiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 370, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Asignacion Familiar:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Fecha Inicio:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Fecha Fin:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Detalles:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        txtdetalles.setEditable(false);
        txtdetalles.setBackground(new java.awt.Color(255, 255, 255));
        txtdetalles.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdetalles.setForeground(new java.awt.Color(0, 0, 204));
        txtdetalles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdetalles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtdetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 370, 30));

        txtobservaciones.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtobservaciones.setForeground(new java.awt.Color(0, 0, 204));
        txtobservaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtobservaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtobservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtobservacionesKeyTyped(evt);
            }
        });
        jPanel2.add(txtobservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 370, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Observaciones:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Estado:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        txtestado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtestado.setForeground(new java.awt.Color(0, 0, 204));
        txtestado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtestado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtestado.addActionListener(this::txtestadoActionPerformed);
        txtestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtestadoKeyTyped(evt);
            }
        });
        jPanel2.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 370, 30));
        jPanel2.add(jDatefechafin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 370, 30));
        jPanel2.add(jDatefechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 370, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1470, 340));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("CONTRATO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 370, 30));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuevo.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        jPanel1.add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Guardar.png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        jPanel1.add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modificar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        jPanel1.add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 200, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar Empleado:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 30));

        TXT_Buscar.addActionListener(this::TXT_BuscarActionPerformed);
        TXT_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyTyped(evt);
            }
        });
        jPanel3.add(TXT_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BUSCAR");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 1470, 50));

        JTABLE_Mantcontrato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mantcontrato.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mantcontrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Contrato", "Id Empleado", "Id Tipo Contrato", "Id Cargo", "Id Sede", "Id Modalidad", "Id Departamento Academico", "Salario", "Horas Semanales", "Asignacion Familiar", "Fecha Inicio", "Fecha Fin", "Detalles", "Observaciones", "Estado"
            }
        ));
        JTABLE_Mantcontrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_MantcontratoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mantcontrato);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1470, 260));

        BTN_Desactivar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/serv.png"))); // NOI18N
        BTN_Desactivar.setText("DAR DE BAJA");
        BTN_Desactivar.addActionListener(this::BTN_DesactivarActionPerformed);
        jPanel1.add(BTN_Desactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 380, 180, 50));

        BTN_PDF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        jPanel1.add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 760, 120, 40));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        jPanel1.add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 760, 120, 40));

        BTN_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salir.png"))); // NOI18N
        BTN_Cerrar.setText("Cerrar");
        BTN_Cerrar.addActionListener(this::BTN_CerrarActionPerformed);
        jPanel1.add(BTN_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 760, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_vercontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_vercontratoActionPerformed
        cargarTabla();
    }//GEN-LAST:event_BTN_vercontratoActionPerformed

    private void txtidempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoKeyTyped

    private void txtidsedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidsedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidsedeActionPerformed

    private void txtidsedeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidsedeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidsedeKeyTyped

    private void txtidtipocontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidtipocontratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtipocontratoActionPerformed

    private void txtidtipocontratoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidtipocontratoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtipocontratoKeyTyped

    private void txtidmodalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidmodalidadKeyTyped

    }//GEN-LAST:event_txtidmodalidadKeyTyped

    private void txtidcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidcargoActionPerformed

    private void txtidcargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidcargoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidcargoKeyTyped

    private void txtsalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalarioKeyTyped

    private void txthorassemanalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorassemanalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorassemanalesActionPerformed

    private void txthorassemanalesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthorassemanalesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorassemanalesKeyTyped

    private void txtasignacionfamiliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtasignacionfamiliarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtasignacionfamiliarActionPerformed

    private void txtasignacionfamiliarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtasignacionfamiliarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtasignacionfamiliarKeyTyped

    private void txtobservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobservacionesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionesKeyTyped

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtestadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoKeyTyped

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
    limpiarCampos();

    BTN_Guardar.setEnabled(true);
    BTN_Modificar.setEnabled(false);
    BTN_Desactivar.setEnabled(false);

    txtidempleado.requestFocus();
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
    if (txtidempleado.getText().trim().isEmpty()
            || txtidtipocontrato.getText().trim().isEmpty()
            || txtidcargo.getText().trim().isEmpty()
            || txtidsede.getText().trim().isEmpty()
            || txtidmodalidad.getText().trim().isEmpty()
            || txtsalario.getText().trim().isEmpty()
            || txthorassemanales.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Complete los campos obligatorios."
        );
        return;
    }

    if (jDatefechainicio.getDate() == null) {
        JOptionPane.showMessageDialog(
                this,
                "Seleccione la fecha de inicio."
        );
        return;
    }

    try {

        String sql = "INSERT INTO contrato "
                + "(id_empleado, id_tipo_contrato, id_cargo, id_sede, "
                + "id_modalidad, id_departamento_academico, salario, "
                + "horas_semanales, asignacion_familiar, fecha_inicio, "
                + "fecha_fin, detalles, observaciones, estado) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setInt(1, Integer.parseInt(txtidempleado.getText()));
            ps.setInt(2, Integer.parseInt(txtidtipocontrato.getText()));
            ps.setInt(3, Integer.parseInt(txtidcargo.getText()));
            ps.setInt(4, Integer.parseInt(txtidsede.getText()));
            ps.setInt(5, Integer.parseInt(txtidmodalidad.getText()));

            if (txtiddepartamentoacademico.getText().trim().isEmpty()) {
                ps.setNull(6, java.sql.Types.INTEGER);
            } else {
                ps.setInt(6,
                        Integer.parseInt(txtiddepartamentoacademico.getText()));
            }

            ps.setBigDecimal(7,
                    new java.math.BigDecimal(txtsalario.getText()));

            ps.setInt(8,
                    Integer.parseInt(txthorassemanales.getText()));

            if (txtasignacionfamiliar.getText().trim().isEmpty()) {
                ps.setBigDecimal(
                        9,
                        java.math.BigDecimal.ZERO
                );
            } else {
                ps.setBigDecimal(
                        9,
                        new java.math.BigDecimal(
                                txtasignacionfamiliar.getText()
                        )
                );
            }

            SimpleDateFormat formato =
                    new SimpleDateFormat("yyyy-MM-dd");

            ps.setString(
                    10,
                    formato.format(jDatefechainicio.getDate())
            );

            if (jDatefechafin.getDate() == null) {
                ps.setNull(11, java.sql.Types.DATE);
            } else {
                ps.setString(
                        11,
                        formato.format(jDatefechafin.getDate())
                );
            }

            ps.setString(12, txtdetalles.getText());
            ps.setString(13, txtobservaciones.getText());

            if (txtestado.getText().trim().isEmpty()) {
                ps.setString(14, "ACTIVO");
            } else {
                ps.setString(14, txtestado.getText());
            }

            ps.executeUpdate();
        }

        limpiarCampos();

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Los campos numéricos contienen valores incorrectos."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al guardar el contrato: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
    if (txtidcontrato.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Seleccione un contrato de la tabla."
        );
        return;
    }

    try {

        String sql = "UPDATE contrato SET "
                + "id_empleado = ?, "
                + "id_tipo_contrato = ?, "
                + "id_cargo = ?, "
                + "id_sede = ?, "
                + "id_modalidad = ?, "
                + "id_departamento_academico = ?, "
                + "salario = ?, "
                + "horas_semanales = ?, "
                + "asignacion_familiar = ?, "
                + "fecha_inicio = ?, "
                + "fecha_fin = ?, "
                + "detalles = ?, "
                + "observaciones = ?, "
                + "estado = ? "
                + "WHERE id_contrato = ?";

        try (PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setInt(1,
                    Integer.parseInt(txtidempleado.getText()));

            ps.setInt(2,
                    Integer.parseInt(txtidtipocontrato.getText()));

            ps.setInt(3,
                    Integer.parseInt(txtidcargo.getText()));

            ps.setInt(4,
                    Integer.parseInt(txtidsede.getText()));

            ps.setInt(5,
                    Integer.parseInt(txtidmodalidad.getText()));

            if (txtiddepartamentoacademico.getText().trim().isEmpty()) {
                ps.setNull(6, java.sql.Types.INTEGER);
            } else {
                ps.setInt(6,
                        Integer.parseInt(
                                txtiddepartamentoacademico.getText()
                        ));
            }

            ps.setBigDecimal(
                    7,
                    new java.math.BigDecimal(txtsalario.getText())
            );

            ps.setInt(
                    8,
                    Integer.parseInt(txthorassemanales.getText())
            );

            if (txtasignacionfamiliar.getText().trim().isEmpty()) {
                ps.setBigDecimal(
                        9,
                        java.math.BigDecimal.ZERO
                );
            } else {
                ps.setBigDecimal(
                        9,
                        new java.math.BigDecimal(
                                txtasignacionfamiliar.getText()
                        )
                );
            }

            SimpleDateFormat formato =
                    new SimpleDateFormat("yyyy-MM-dd");

            ps.setString(
                    10,
                    formato.format(jDatefechainicio.getDate())
            );

            if (jDatefechafin.getDate() == null) {
                ps.setNull(11, java.sql.Types.DATE);
            } else {
                ps.setString(
                        11,
                        formato.format(jDatefechafin.getDate())
                );
            }

            ps.setString(12, txtdetalles.getText());
            ps.setString(13, txtobservaciones.getText());

            ps.setString(
                    14,
                    txtestado.getText().trim().isEmpty()
                    ? "ACTIVO"
                    : txtestado.getText()
            );

            ps.setInt(
                    15,
                    Integer.parseInt(txtidcontrato.getText())
            );

            ps.executeUpdate();
        }

        limpiarCampos();

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        cargarTabla();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Revise los campos numéricos."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al modificar: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void TXT_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_BuscarActionPerformed

    private void TXT_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyReleased
    String buscar = TXT_Buscar.getText().trim();

    DefaultTableModel modelo =
            (DefaultTableModel) JTABLE_Mantcontrato.getModel();

    modelo.setRowCount(0);

    String sql = "SELECT "
            + "id_contrato, id_empleado, id_tipo_contrato, "
            + "id_cargo, id_sede, id_modalidad, "
            + "id_departamento_academico, salario, "
            + "horas_semanales, asignacion_familiar, "
            + "fecha_inicio, fecha_fin, detalles, "
            + "observaciones, estado "
            + "FROM contrato "
            + "WHERE CAST(id_contrato AS CHAR) LIKE ? "
            + "OR CAST(id_empleado AS CHAR) LIKE ? "
            + "OR estado LIKE ? "
            + "ORDER BY id_contrato";

    try (PreparedStatement ps = cn.prepareStatement(sql)) {

        String texto = "%" + buscar + "%";

        ps.setString(1, texto);
        ps.setString(2, texto);
        ps.setString(3, texto);

        try (ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {

                modelo.addRow(new Object[]{
                    rs.getInt("id_contrato"),
                    rs.getInt("id_empleado"),
                    rs.getInt("id_tipo_contrato"),
                    rs.getInt("id_cargo"),
                    rs.getInt("id_sede"),
                    rs.getInt("id_modalidad"),
                    rs.getInt("id_departamento_academico"),
                    rs.getBigDecimal("salario"),
                    rs.getInt("horas_semanales"),
                    rs.getBigDecimal("asignacion_familiar"),
                    rs.getDate("fecha_inicio"),
                    rs.getDate("fecha_fin"),
                    rs.getString("detalles"),
                    rs.getString("observaciones"),
                    rs.getString("estado")
                });
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al buscar: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_TXT_BuscarKeyReleased

    private void TXT_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyTyped

    }//GEN-LAST:event_TXT_BuscarKeyTyped

    private void JTABLE_MantcontratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_MantcontratoMouseClicked
    int fila = JTABLE_Mantcontrato.getSelectedRow();

    if (fila == -1) {
        return;
    }

    txtidcontrato.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 0).toString()
    );

    txtidempleado.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 1).toString()
    );

    txtidtipocontrato.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 2).toString()
    );

    txtidcargo.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 3).toString()
    );

    txtidsede.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 4).toString()
    );

    txtidmodalidad.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 5).toString()
    );

    Object departamento =
            JTABLE_Mantcontrato.getValueAt(fila, 6);

    txtiddepartamentoacademico.setText(
            departamento == null ? "" : departamento.toString()
    );

    txtsalario.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 7).toString()
    );

    txthorassemanales.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 8).toString()
    );

    txtasignacionfamiliar.setText(
            JTABLE_Mantcontrato.getValueAt(fila, 9).toString()
    );

    Object fechaInicio =
            JTABLE_Mantcontrato.getValueAt(fila, 10);

    if (fechaInicio != null) {
        try {
            jDatefechainicio.setDate(
                    new SimpleDateFormat("yyyy-MM-dd")
                            .parse(fechaInicio.toString())
            );
        } catch (Exception e) {
            jDatefechainicio.setDate(null);
        }
    }

    Object fechaFin =
            JTABLE_Mantcontrato.getValueAt(fila, 11);

    if (fechaFin != null) {
        try {
            jDatefechafin.setDate(
                    new SimpleDateFormat("yyyy-MM-dd")
                            .parse(fechaFin.toString())
            );
        } catch (Exception e) {
            jDatefechafin.setDate(null);
        }
    } else {
        jDatefechafin.setDate(null);
    }

    Object detalles =
            JTABLE_Mantcontrato.getValueAt(fila, 12);

    txtdetalles.setText(
            detalles == null ? "" : detalles.toString()
    );

    Object observaciones =
            JTABLE_Mantcontrato.getValueAt(fila, 13);

    txtobservaciones.setText(
            observaciones == null ? "" : observaciones.toString()
    );

    Object estado =
            JTABLE_Mantcontrato.getValueAt(fila, 14);

    txtestado.setText(
            estado == null ? "" : estado.toString()
    );

    BTN_Guardar.setEnabled(false);
    BTN_Modificar.setEnabled(true);
    BTN_Desactivar.setEnabled(true);
    }//GEN-LAST:event_JTABLE_MantcontratoMouseClicked

    private void BTN_DesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DesactivarActionPerformed
    if (txtidcontrato.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
                this,
                "Seleccione un contrato."
        );
        return;
    }

    try {

        String sql = "UPDATE contrato "
                + "SET estado = 'INACTIVO' "
                + "WHERE id_contrato = ?";

        try (PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setInt(
                    1,
                    Integer.parseInt(txtidcontrato.getText())
            );

            ps.executeUpdate();
        }

        limpiarCampos();

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        cargarTabla();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al dar de baja: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_DesactivarActionPerformed

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void BTN_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BTN_CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_Mantcontrato().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar;
    private javax.swing.JButton BTN_Desactivar;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_vercontrato;
    private javax.swing.JTable JTABLE_Mantcontrato;
    private javax.swing.JTextField TXT_Buscar;
    private com.toedter.calendar.JDateChooser jDatefechafin;
    private com.toedter.calendar.JDateChooser jDatefechainicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtasignacionfamiliar;
    private javax.swing.JTextField txtdetalles;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txthorassemanales;
    private javax.swing.JTextField txtidcargo;
    private javax.swing.JTextField txtidcontrato;
    private javax.swing.JTextField txtiddepartamentoacademico;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtidmodalidad;
    private javax.swing.JTextField txtidsede;
    private javax.swing.JTextField txtidtipocontrato;
    private javax.swing.JTextField txtobservaciones;
    private javax.swing.JTextField txtsalario;
    // End of variables declaration//GEN-END:variables
}
