package proyecto_recursoshumanos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_Mantasistencia extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frm_Mantasistencia.class.getName());
    private Connection cn;

    /**
     * Creates new form frm_Mantasistencia
     */
    public frm_Mantasistencia() {

        initComponents();

        setLocationRelativeTo(null);

        // CONEXIÓN A MYSQL
        Conexion_bd_Luis conexionBD = new Conexion_bd_Luis();
        cn = conexionBD.conectar();

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        // Tabla vacía al iniciar
        DefaultTableModel modelo
                = (DefaultTableModel) JTABLE_Mantpermisolicencia.getModel();

        modelo.setRowCount(0);
    }

private void limpiarCampos() {

    txtidasistencia.setText("");
    txtidempleado.setText("");
    txtestadoasistencia.setText("");
    jDatefecha.setDate(null);
    txthoraentrada.setText("");
    txthorasalida.setText("");
    txtminutostardanza.setText("");
    txtobservaciones.setText("");

    JTABLE_Mantpermisolicencia.clearSelection();
}

private void cargarTabla() {

    DefaultTableModel modelo =
            (DefaultTableModel) JTABLE_Mantpermisolicencia.getModel();

    modelo.setRowCount(0);

    String sql =
            "SELECT id_asistencia, "
            + "id_empleado, "
            + "id_estado_asistencia, "
            + "fecha, "
            + "hora_entrada, "
            + "hora_salida, "
            + "minutos_tardanza, "
            + "observaciones "
            + "FROM asistencias "
            + "ORDER BY id_asistencia";

    try (PreparedStatement ps = cn.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {

            modelo.addRow(new Object[]{
                rs.getInt("id_asistencia"),
                rs.getInt("id_empleado"),
                rs.getInt("id_estado_asistencia"),
                rs.getDate("fecha"),
                rs.getTime("hora_entrada"),
                rs.getTime("hora_salida"),
                rs.getInt("minutos_tardanza"),
                rs.getString("observaciones")
            });
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al cargar asistencias: "
                + e.getMessage()
        );
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidasistencia = new javax.swing.JTextField();
        BTN_verasistencia = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidempleado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthorasalida = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtestadoasistencia = new javax.swing.JTextField();
        jDatefecha = new com.toedter.calendar.JDateChooser();
        txtminutostardanza = new javax.swing.JTextField();
        txthoraentrada = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtobservaciones = new javax.swing.JTextField();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        BTN_Desactivar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_Buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mantpermisolicencia = new javax.swing.JTable();
        BTN_PDF = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        BTN_Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ASISTENCIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 370, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id Asistencia:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Observaciones:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        txtidasistencia.setEditable(false);
        txtidasistencia.setBackground(new java.awt.Color(255, 255, 255));
        txtidasistencia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidasistencia.setForeground(new java.awt.Color(0, 0, 204));
        txtidasistencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidasistencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidasistencia.addActionListener(this::txtidasistenciaActionPerformed);
        jPanel2.add(txtidasistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 370, 30));

        BTN_verasistencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_verasistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        BTN_verasistencia.setText("VER ASISTENCIA");
        BTN_verasistencia.setActionCommand("VER Permiso Licencia");
        BTN_verasistencia.addActionListener(this::BTN_verasistenciaActionPerformed);
        jPanel2.add(BTN_verasistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 280, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Id Empleado:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Fecha:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Hora Entrada:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtidempleado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidempleado.setForeground(new java.awt.Color(0, 0, 204));
        txtidempleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidempleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidempleado.addActionListener(this::txtidempleadoActionPerformed);
        txtidempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyTyped(evt);
            }
        });
        jPanel2.add(txtidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 370, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Minutos Tardanza:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txthorasalida.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txthorasalida.setForeground(new java.awt.Color(0, 0, 204));
        txthorasalida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthorasalida.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txthorasalida.addActionListener(this::txthorasalidaActionPerformed);
        txthorasalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthorasalidaKeyTyped(evt);
            }
        });
        jPanel2.add(txthorasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 370, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Id Estado Asistencia:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtestadoasistencia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtestadoasistencia.setForeground(new java.awt.Color(0, 0, 204));
        txtestadoasistencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtestadoasistencia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtestadoasistencia.addActionListener(this::txtestadoasistenciaActionPerformed);
        txtestadoasistencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtestadoasistenciaKeyTyped(evt);
            }
        });
        jPanel2.add(txtestadoasistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 370, 30));
        jPanel2.add(jDatefecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 370, -1));

        txtminutostardanza.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtminutostardanza.setForeground(new java.awt.Color(0, 0, 204));
        txtminutostardanza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtminutostardanza.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtminutostardanza.addActionListener(this::txtminutostardanzaActionPerformed);
        txtminutostardanza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtminutostardanzaKeyTyped(evt);
            }
        });
        jPanel2.add(txtminutostardanza, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 370, 30));

        txthoraentrada.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txthoraentrada.setForeground(new java.awt.Color(0, 0, 204));
        txthoraentrada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txthoraentrada.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txthoraentrada.addActionListener(this::txthoraentradaActionPerformed);
        txthoraentrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthoraentradaKeyTyped(evt);
            }
        });
        jPanel2.add(txthoraentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 370, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Hora Salida:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtobservaciones.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtobservaciones.setForeground(new java.awt.Color(0, 0, 204));
        txtobservaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtobservaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtobservaciones.addActionListener(this::txtobservacionesActionPerformed);
        txtobservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtobservacionesKeyTyped(evt);
            }
        });
        jPanel2.add(txtobservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 370, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 870, 350));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuevo.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        jPanel1.add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Guardar.png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        jPanel1.add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modificar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        jPanel1.add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 200, 50));

        BTN_Desactivar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/serv.png"))); // NOI18N
        BTN_Desactivar.setText("DAR DE BAJA");
        BTN_Desactivar.addActionListener(this::BTN_DesactivarActionPerformed);
        jPanel1.add(BTN_Desactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 180, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar Asistencia:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 30));

        TXT_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyTyped(evt);
            }
        });
        jPanel3.add(TXT_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BUSCAR");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 890, 50));

        JTABLE_Mantpermisolicencia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mantpermisolicencia.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mantpermisolicencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Asistencia", "Id Empleado", "Id Estado Asistencia", "Fecha", "Hora Entrada", "Hora Salida", "Minutos Tardanza", "Observaciones"
            }
        ));
        JTABLE_Mantpermisolicencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_MantpermisolicenciaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mantpermisolicencia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 890, 260));

        BTN_PDF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        jPanel1.add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 800, 120, 40));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        jPanel1.add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 800, 120, 40));

        BTN_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salir.png"))); // NOI18N
        BTN_Cerrar.setText("Cerrar");
        BTN_Cerrar.addActionListener(this::BTN_CerrarActionPerformed);
        jPanel1.add(BTN_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 800, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_verasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_verasistenciaActionPerformed
        cargarTabla();
    }//GEN-LAST:event_BTN_verasistenciaActionPerformed

    private void txtidempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoKeyTyped

    private void txthorasalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorasalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasalidaActionPerformed

    private void txthorasalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthorasalidaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasalidaKeyTyped

    private void txtestadoasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoasistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoasistenciaActionPerformed

    private void txtestadoasistenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestadoasistenciaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoasistenciaKeyTyped

    private void txtminutostardanzaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtminutostardanzaKeyTyped

    }//GEN-LAST:event_txtminutostardanzaKeyTyped

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
        txtidasistencia.setText("");
        txtidempleado.setText("");
        txtestadoasistencia.setText("");
        txthoraentrada.setText("");
        txthorasalida.setText("");
        txtminutostardanza.setText("");

        jDatefecha.setDate(null);

        BTN_Guardar.setEnabled(true);
        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        txtidempleado.requestFocus();
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
        if (txtidempleado.getText().trim().isEmpty()
                || txtestadoasistencia.getText().trim().isEmpty()
                || txthoraentrada.getText().trim().isEmpty()
                || txthorasalida.getText().trim().isEmpty()
                || txtminutostardanza.getText().trim().isEmpty()
                || jDatefecha.getDate() == null) {

            JOptionPane.showMessageDialog(this,
                    "Complete todos los campos obligatorios.");

            return;
        }

        SimpleDateFormat formatoFecha
                = new SimpleDateFormat("yyyy-MM-dd");

        String fecha
                = formatoFecha.format(jDatefecha.getDate());

        String sql = "INSERT INTO asistencia "
                + "(id_empleado, id_estado_asistencia, fecha, "
                + "hora_entrada, hora_salida, observaciones) "
                + "VALUES (?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setInt(1,
                    Integer.parseInt(txtidempleado.getText().trim()));

            ps.setInt(2,
                    Integer.parseInt(txtestadoasistencia.getText().trim()));

            ps.setString(3, fecha);

            ps.setString(4,
                    txthoraentrada.getText().trim());

            ps.setString(5,
                    txthorasalida.getText().trim());

            ps.setString(6,
                    txtminutostardanza.getText().trim());

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Asistencia registrada correctamente.");

            limpiarCampos();

            BTN_Guardar.setEnabled(false);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Los IDs deben contener solamente números.");

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Error al guardar asistencia: " + e.getMessage());
        }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
    if (txtidasistencia.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione una asistencia de la tabla."
        );

        return;
    }

    if (txtidempleado.getText().trim().isEmpty()
            || txtestadoasistencia.getText().trim().isEmpty()
            || txthoraentrada.getText().trim().isEmpty()
            || txthorasalida.getText().trim().isEmpty()
            || txtminutostardanza.getText().trim().isEmpty()
            || jDatefecha.getDate() == null) {

        JOptionPane.showMessageDialog(
                this,
                "Complete todos los campos."
        );

        return;
    }

    SimpleDateFormat formatoFecha =
            new SimpleDateFormat("yyyy-MM-dd");

    String fecha =
            formatoFecha.format(jDatefecha.getDate());

    String sql = "UPDATE asistencias SET "
            + "id_empleado = ?, "
            + "id_estado_asistencia = ?, "
            + "fecha = ?, "
            + "hora_entrada = ?, "
            + "hora_salida = ?, "
            + "observaciones = ? "
            + "WHERE id_asistencia = ?";

    try (PreparedStatement ps = cn.prepareStatement(sql)) {

        ps.setInt(1,
                Integer.parseInt(
                        txtidempleado.getText().trim()
                ));

        ps.setInt(2,
                Integer.parseInt(
                        txtestadoasistencia.getText().trim()
                ));

        ps.setString(3, fecha);

        ps.setString(4,
                txthoraentrada.getText().trim());

        ps.setString(5,
                txthorasalida.getText().trim());

        ps.setString(6,
                txtminutostardanza.getText().trim());

        ps.setInt(7,
                Integer.parseInt(
                        txtidasistencia.getText().trim()
                ));

        ps.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Asistencia modificada correctamente."
        );

        limpiarCampos();

        BTN_Guardar.setEnabled(false);
        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        cargarTabla();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Los IDs deben contener solamente números."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al modificar: " + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_DesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DesactivarActionPerformed
        if (txtidasistencia.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this,
                    "Seleccione una asistencia de la tabla.");

            return;
        }

        String sql = "UPDATE asistencia "
                + "SET estado = 'INACTIVO' "
                + "WHERE id_asistencia = ?";

        try (PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setInt(1,
                    Integer.parseInt(txtidasistencia.getText().trim()));

            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Asistencia dada de baja correctamente.");

            limpiarCampos();

            BTN_Modificar.setEnabled(false);
            BTN_Desactivar.setEnabled(false);

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Error al dar de baja: " + e.getMessage());

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "El ID debe ser numérico.");
        }
    }//GEN-LAST:event_BTN_DesactivarActionPerformed

    private void TXT_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyReleased
        String buscar = TXT_Buscar.getText().trim();

        DefaultTableModel modelo
                = (DefaultTableModel) JTABLE_Mantpermisolicencia.getModel();

        modelo.setRowCount(0);

        String sql = "SELECT id_asistencia, id_empleado, "
                + "id_estado_asistencia, fecha, hora_entrada, "
                + "hora_salida, observaciones "
                + "FROM asistencia "
                + "WHERE CAST(id_asistencia AS CHAR) LIKE ? "
                + "ORDER BY id_asistencia";

        try (PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setString(1, "%" + buscar + "%");

            try (ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {

                    modelo.addRow(new Object[]{
                        rs.getInt("id_asistencia"),
                        rs.getInt("id_empleado"),
                        rs.getInt("id_estado_asistencia"),
                        rs.getDate("fecha"),
                        rs.getTime("hora_entrada"),
                        rs.getTime("hora_salida"),
                        rs.getString("observaciones")
                    });
                }
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Error al buscar asistencia: " + e.getMessage());
        }
    }//GEN-LAST:event_TXT_BuscarKeyReleased

    private void TXT_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyTyped

    }//GEN-LAST:event_TXT_BuscarKeyTyped

    private void JTABLE_MantpermisolicenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_MantpermisolicenciaMouseClicked
        int fila = JTABLE_Mantpermisolicencia.getSelectedRow();

        if (fila >= 0) {

            txtidasistencia.setText(
                    JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 0).toString());

            txtidempleado.setText(
                    JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 1).toString());

            txtestadoasistencia.setText(
                    JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 2).toString());

            Object fecha
                    = JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 3);

            if (fecha instanceof java.util.Date) {
                jDatefecha.setDate((java.util.Date) fecha);
            }

            txthoraentrada.setText(
                    JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 4).toString());

            txthorasalida.setText(
                    JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 5).toString());

            txtminutostardanza.setText(
                    JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 6).toString());
            txtobservaciones.setText(
                    JTABLE_Mantpermisolicencia
                            .getValueAt(fila, 7).toString());
            BTN_Guardar.setEnabled(false);
            BTN_Modificar.setEnabled(true);
            BTN_Desactivar.setEnabled(true);
        }
    }//GEN-LAST:event_JTABLE_MantpermisolicenciaMouseClicked

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void BTN_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BTN_CerrarActionPerformed

    private void txthoraentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthoraentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraentradaActionPerformed

    private void txthoraentradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthoraentradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txthoraentradaKeyTyped

    private void txtminutostardanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtminutostardanzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtminutostardanzaActionPerformed

    private void txtobservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionesActionPerformed

    private void txtobservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobservacionesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionesKeyTyped

    private void txtidempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoActionPerformed

    private void txtidasistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidasistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidasistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_Mantasistencia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar;
    private javax.swing.JButton BTN_Desactivar;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_verasistencia;
    private javax.swing.JTable JTABLE_Mantpermisolicencia;
    private javax.swing.JTextField TXT_Buscar;
    private com.toedter.calendar.JDateChooser jDatefecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtestadoasistencia;
    private javax.swing.JTextField txthoraentrada;
    private javax.swing.JTextField txthorasalida;
    private javax.swing.JTextField txtidasistencia;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtminutostardanza;
    private javax.swing.JTextField txtobservaciones;
    // End of variables declaration//GEN-END:variables
}
