package proyecto_recursoshumanos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_Mantempleado extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(
                    frm_Mantempleado.class.getName());

    private Connection cn;
    
public frm_Mantempleado() {

    initComponents();

    setLocationRelativeTo(null);

    // CONEXIÓN A MYSQL
    Conexion_bd_Luis conexionBD =
            new Conexion_bd_Luis();

    cn = conexionBD.conectar();

    // BOTONES DESACTIVADOS AL INICIAR
    BTN_Guardar.setEnabled(false);
    BTN_Modificar.setEnabled(false);
    BTN_Desactivar.setEnabled(false);

    // TABLA VACÍA AL INICIAR
    DefaultTableModel modelo =
            (DefaultTableModel)
            JTABLE_Mantempleadocapacitacion.getModel();

    modelo.setRowCount(0);
}

private void limpiarCampos() {

    txtidempleado.setText("");
    txtidtipodocumento.setText("");
    txtidgenero.setText("");
    txtidprofesion.setText("");
    txtiddistrito.setText("");
    txtnumerodocumento.setText("");
    txtnombres.setText("");
    txtapellidos.setText("");
    txttelefono1.setText("");
    txttelefono2.setText("");
    jDatefechanacimiento.setDate(null);
    txtdireccionactual.setText("");
    txtcorreo1.setText("");
    txtcorreo2.setText("");
    txtobservaciones.setText("");
    txtestado.setText("");

    JTABLE_Mantempleadocapacitacion.clearSelection();
}

private void cargarTabla() {

    DefaultTableModel modelo =
            (DefaultTableModel)
            JTABLE_Mantempleadocapacitacion.getModel();

    modelo.setRowCount(0);

    String sql =
            "SELECT id_empleado, "
            + "id_tipo_documento, "
            + "id_genero, "
            + "id_profesion, "
            + "id_distrito, "
            + "numero_documento, "
            + "nombres, "
            + "apellidos, "
            + "telefono1, "
            + "telefono2, "
            + "fecha_nacimiento, "
            + "direccion_actual, "
            + "correo1, "
            + "correo2, "
            + "observaciones, "
            + "estado "
            + "FROM empleado "
            + "ORDER BY id_empleado";

    try {

        if (cn == null || cn.isClosed()) {

            Conexion_bd_Luis conexionBD =
                    new Conexion_bd_Luis();

            cn = conexionBD.conectar();
        }

        try (PreparedStatement ps =
                cn.prepareStatement(sql);
             ResultSet rs =
                ps.executeQuery()) {

            while (rs.next()) {

                modelo.addRow(new Object[]{

                    rs.getInt("id_empleado"),

                    rs.getInt("id_tipo_documento"),

                    rs.getInt("id_genero"),

                    rs.getInt("id_profesion"),

                    rs.getInt("id_distrito"),

                    rs.getString("numero_documento"),

                    rs.getString("nombres"),

                    rs.getString("apellidos"),

                    rs.getString("telefono1"),

                    rs.getString("telefono2"),

                    rs.getDate("fecha_nacimiento"),

                    rs.getString("direccion_actual"),

                    rs.getString("correo1"),

                    rs.getString("correo2"),

                    rs.getString("observaciones"),

                    rs.getString("estado")
                });
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al cargar empleados:\n"
                + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidempleado = new javax.swing.JTextField();
        BTN_verempleadocapacitacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidtipodocumento = new javax.swing.JTextField();
        txtiddistrito = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtidgenero = new javax.swing.JTextField();
        txtnumerodocumento = new javax.swing.JTextField();
        txtidprofesion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txttelefono1 = new javax.swing.JTextField();
        txttelefono2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtdireccionactual = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtcorreo1 = new javax.swing.JTextField();
        txtcorreo2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtobservaciones = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jDatefechanacimiento = new com.toedter.calendar.JDateChooser();
        BTN_Cerrar = new javax.swing.JButton();
        BTN_EXCEL = new javax.swing.JButton();
        BTN_PDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTABLE_Mantempleadocapacitacion = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_Buscar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BTN_Nuevo = new javax.swing.JButton();
        BTN_Guardar = new javax.swing.JButton();
        BTN_Modificar = new javax.swing.JButton();
        BTN_Desactivar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("EMPLEADO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 370, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 51), null));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id Empleado:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Numero Documento:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtidempleado.setEditable(false);
        txtidempleado.setBackground(new java.awt.Color(255, 255, 255));
        txtidempleado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidempleado.setForeground(new java.awt.Color(0, 0, 204));
        txtidempleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidempleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtidempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 370, 30));

        BTN_verempleadocapacitacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_verempleadocapacitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        BTN_verempleadocapacitacion.setText("VER EMPLEADO");
        BTN_verempleadocapacitacion.setActionCommand("VER Permiso Licencia");
        BTN_verempleadocapacitacion.addActionListener(this::BTN_verempleadocapacitacionActionPerformed);
        jPanel2.add(BTN_verempleadocapacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 280, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Id Tipo Documento:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Id Profesion:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Id Distrito:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtidtipodocumento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidtipodocumento.setForeground(new java.awt.Color(0, 0, 204));
        txtidtipodocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidtipodocumento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidtipodocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidtipodocumentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtidtipodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 370, 30));

        txtiddistrito.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtiddistrito.setForeground(new java.awt.Color(0, 0, 204));
        txtiddistrito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtiddistrito.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtiddistrito.addActionListener(this::txtiddistritoActionPerformed);
        txtiddistrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtiddistritoKeyTyped(evt);
            }
        });
        jPanel2.add(txtiddistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 370, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Id Genero:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txtidgenero.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidgenero.setForeground(new java.awt.Color(0, 0, 204));
        txtidgenero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidgenero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidgenero.addActionListener(this::txtidgeneroActionPerformed);
        txtidgenero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidgeneroKeyTyped(evt);
            }
        });
        jPanel2.add(txtidgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 370, 30));

        txtnumerodocumento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnumerodocumento.setForeground(new java.awt.Color(0, 0, 204));
        txtnumerodocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnumerodocumento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtnumerodocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumerodocumentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtnumerodocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 370, 30));

        txtidprofesion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtidprofesion.setForeground(new java.awt.Color(0, 0, 204));
        txtidprofesion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidprofesion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtidprofesion.addActionListener(this::txtidprofesionActionPerformed);
        txtidprofesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidprofesionKeyTyped(evt);
            }
        });
        jPanel2.add(txtidprofesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 370, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nombres:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        txtnombres.setEditable(false);
        txtnombres.setBackground(new java.awt.Color(255, 255, 255));
        txtnombres.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnombres.setForeground(new java.awt.Color(0, 0, 204));
        txtnombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombres.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 370, 30));

        txtapellidos.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtapellidos.setForeground(new java.awt.Color(0, 0, 204));
        txtapellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapellidos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        jPanel2.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 370, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Apellidos:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Telefono 1:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        txttelefono1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txttelefono1.setForeground(new java.awt.Color(0, 0, 204));
        txttelefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttelefono1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttelefono1.addActionListener(this::txttelefono1ActionPerformed);
        txttelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefono1KeyTyped(evt);
            }
        });
        jPanel2.add(txttelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 370, 30));

        txttelefono2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txttelefono2.setForeground(new java.awt.Color(0, 0, 204));
        txttelefono2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttelefono2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txttelefono2.addActionListener(this::txttelefono2ActionPerformed);
        txttelefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefono2KeyTyped(evt);
            }
        });
        jPanel2.add(txttelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 370, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Telefono 2:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Fecha nacimiento:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Direccion Actual:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        txtdireccionactual.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtdireccionactual.setForeground(new java.awt.Color(0, 0, 204));
        txtdireccionactual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdireccionactual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtdireccionactual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionactualKeyTyped(evt);
            }
        });
        jPanel2.add(txtdireccionactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 370, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Correo 1:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        txtcorreo1.setEditable(false);
        txtcorreo1.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreo1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcorreo1.setForeground(new java.awt.Color(0, 0, 204));
        txtcorreo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(txtcorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 370, 30));

        txtcorreo2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcorreo2.setForeground(new java.awt.Color(0, 0, 204));
        txtcorreo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcorreo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreo2KeyTyped(evt);
            }
        });
        jPanel2.add(txtcorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 370, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Correo 2:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Observaciones:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        txtobservaciones.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtobservaciones.setForeground(new java.awt.Color(0, 0, 204));
        txtobservaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtobservaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtobservaciones.addActionListener(this::txtobservacionesActionPerformed);
        txtobservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtobservacionesKeyTyped(evt);
            }
        });
        jPanel2.add(txtobservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 370, 30));

        txtestado.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtestado.setForeground(new java.awt.Color(0, 0, 204));
        txtestado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtestado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtestado.addActionListener(this::txtestadoActionPerformed);
        txtestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtestadoKeyTyped(evt);
            }
        });
        jPanel2.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 370, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Estado:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));
        jPanel2.add(jDatefechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 370, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1460, 340));

        BTN_Cerrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salir.png"))); // NOI18N
        BTN_Cerrar.setText("Cerrar");
        BTN_Cerrar.addActionListener(this::BTN_CerrarActionPerformed);
        jPanel1.add(BTN_Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 780, 130, 40));

        BTN_EXCEL.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_EXCEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/excel.png"))); // NOI18N
        BTN_EXCEL.setText("Exportar");
        BTN_EXCEL.addActionListener(this::BTN_EXCELActionPerformed);
        jPanel1.add(BTN_EXCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 780, 120, 40));

        BTN_PDF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        BTN_PDF.setText("Exportar");
        BTN_PDF.addActionListener(this::BTN_PDFActionPerformed);
        jPanel1.add(BTN_PDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 780, 120, 40));

        JTABLE_Mantempleadocapacitacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JTABLE_Mantempleadocapacitacion.setForeground(new java.awt.Color(0, 0, 204));
        JTABLE_Mantempleadocapacitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Empleado", "Id Tipo Documento", "Id Genero", "Id Profesion", "Id Distrito", "Numero Documento", "Nombres", "Apellidos", "Telefono 1", "Telefono 2", "Fecha Nacimiento", "Direccion Actual", "Correo 1", "Correo 2", "Observaciones", "Estado"
            }
        ));
        JTABLE_Mantempleadocapacitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTABLE_MantempleadocapacitacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTABLE_Mantempleadocapacitacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 1450, 260));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar Empleado:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 30));

        TXT_Buscar.addActionListener(this::TXT_BuscarActionPerformed);
        TXT_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_BuscarKeyTyped(evt);
            }
        });
        jPanel3.add(TXT_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BUSCAR");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 120, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 1450, 50));

        BTN_Nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nuevo.png"))); // NOI18N
        BTN_Nuevo.setText("NUEVO");
        BTN_Nuevo.addActionListener(this::BTN_NuevoActionPerformed);
        jPanel1.add(BTN_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 190, 50));

        BTN_Guardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Guardar.png"))); // NOI18N
        BTN_Guardar.setText("GUARDAR");
        BTN_Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_GuardarMouseClicked(evt);
            }
        });
        BTN_Guardar.addActionListener(this::BTN_GuardarActionPerformed);
        jPanel1.add(BTN_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 190, 50));

        BTN_Modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modificar.png"))); // NOI18N
        BTN_Modificar.setText("MODIFICAR");
        BTN_Modificar.addActionListener(this::BTN_ModificarActionPerformed);
        jPanel1.add(BTN_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, 200, 50));

        BTN_Desactivar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTN_Desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/serv.png"))); // NOI18N
        BTN_Desactivar.setText("DAR DE BAJA");
        BTN_Desactivar.addActionListener(this::BTN_DesactivarActionPerformed);
        jPanel1.add(BTN_Desactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 400, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_verempleadocapacitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_verempleadocapacitacionActionPerformed
        cargarTabla();
    }//GEN-LAST:event_BTN_verempleadocapacitacionActionPerformed

    private void txtidtipodocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidtipodocumentoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidtipodocumentoKeyTyped

    private void txtiddistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtiddistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiddistritoActionPerformed

    private void txtiddistritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtiddistritoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtiddistritoKeyTyped

    private void txtidgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidgeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidgeneroActionPerformed

    private void txtidgeneroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidgeneroKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidgeneroKeyTyped

    private void txtnumerodocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumerodocumentoKeyTyped

    }//GEN-LAST:event_txtnumerodocumentoKeyTyped

    private void txtidprofesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprofesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprofesionActionPerformed

    private void txtidprofesionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidprofesionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprofesionKeyTyped

    private void BTN_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CerrarActionPerformed
        dispose();
    }//GEN-LAST:event_BTN_CerrarActionPerformed

    private void BTN_EXCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EXCELActionPerformed

    }//GEN-LAST:event_BTN_EXCELActionPerformed

    private void BTN_PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PDFActionPerformed

    }//GEN-LAST:event_BTN_PDFActionPerformed

    private void JTABLE_MantempleadocapacitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTABLE_MantempleadocapacitacionMouseClicked
    int fila =
            JTABLE_Mantempleadocapacitacion
                    .getSelectedRow();

    if (fila < 0) {
        return;
    }

    txtidempleado.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 0)
                    .toString()
    );

    txtidtipodocumento.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 1)
                    .toString()
    );

    txtidgenero.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 2)
                    .toString()
    );

    txtidprofesion.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 3)
                    .toString()
    );

    txtiddistrito.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 4)
                    .toString()
    );

    txtnumerodocumento.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 5)
                    .toString()
    );

    txtnombres.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 6)
                    .toString()
    );

    txtapellidos.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 7)
                    .toString()
    );

    txttelefono1.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 8)
                    .toString()
    );

    txttelefono2.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 9)
                    .toString()
    );

    Object fecha =
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 10);

    if (fecha instanceof java.util.Date) {
        jDatefechanacimiento.setDate(
                (java.util.Date) fecha
        );
    }

    txtdireccionactual.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 11)
                    .toString()
    );

    txtcorreo1.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 12)
                    .toString()
    );

    txtcorreo2.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 13)
                    .toString()
    );

    txtobservaciones.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 14)
                    .toString()
    );

    txtestado.setText(
            JTABLE_Mantempleadocapacitacion
                    .getValueAt(fila, 15)
                    .toString()
    );

    BTN_Guardar.setEnabled(false);
    BTN_Modificar.setEnabled(true);
    BTN_Desactivar.setEnabled(true);
    }//GEN-LAST:event_JTABLE_MantempleadocapacitacionMouseClicked

    private void TXT_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_BuscarActionPerformed

    private void TXT_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyReleased
    String buscar =
            TXT_Buscar.getText().trim();

    DefaultTableModel modelo =
            (DefaultTableModel)
            JTABLE_Mantempleadocapacitacion.getModel();

    modelo.setRowCount(0);

    String sql =
            "SELECT id_empleado, "
            + "id_tipo_documento, "
            + "id_genero, "
            + "id_profesion, "
            + "id_distrito, "
            + "numero_documento, "
            + "nombres, "
            + "apellidos, "
            + "telefono1, "
            + "telefono2, "
            + "fecha_nacimiento, "
            + "direccion_actual, "
            + "correo1, "
            + "correo2, "
            + "observaciones, "
            + "estado "
            + "FROM empleado "
            + "WHERE CAST(id_empleado AS CHAR) LIKE ? "
            + "OR numero_documento LIKE ? "
            + "OR nombres LIKE ? "
            + "OR apellidos LIKE ? "
            + "ORDER BY id_empleado";

    try (PreparedStatement ps =
            cn.prepareStatement(sql)) {

        String texto = "%" + buscar + "%";

        ps.setString(1, texto);
        ps.setString(2, texto);
        ps.setString(3, texto);
        ps.setString(4, texto);

        try (ResultSet rs =
                ps.executeQuery()) {

            while (rs.next()) {

                modelo.addRow(new Object[]{

                    rs.getInt("id_empleado"),
                    rs.getInt("id_tipo_documento"),
                    rs.getInt("id_genero"),
                    rs.getInt("id_profesion"),
                    rs.getInt("id_distrito"),
                    rs.getString("numero_documento"),
                    rs.getString("nombres"),
                    rs.getString("apellidos"),
                    rs.getString("telefono1"),
                    rs.getString("telefono2"),
                    rs.getDate("fecha_nacimiento"),
                    rs.getString("direccion_actual"),
                    rs.getString("correo1"),
                    rs.getString("correo2"),
                    rs.getString("observaciones"),
                    rs.getString("estado")
                });
            }
        }

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al buscar empleado:\n"
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_TXT_BuscarKeyReleased

    private void TXT_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BuscarKeyTyped

    }//GEN-LAST:event_TXT_BuscarKeyTyped

    private void BTN_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_NuevoActionPerformed
    limpiarCampos();

    BTN_Guardar.setEnabled(true);
    BTN_Modificar.setEnabled(false);
    BTN_Desactivar.setEnabled(false);

    txtidtipodocumento.requestFocus();        
    }//GEN-LAST:event_BTN_NuevoActionPerformed

    private void BTN_GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_GuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_GuardarMouseClicked

    private void BTN_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GuardarActionPerformed
    if (txtidtipodocumento.getText().trim().isEmpty()
            || txtidgenero.getText().trim().isEmpty()
            || txtidprofesion.getText().trim().isEmpty()
            || txtiddistrito.getText().trim().isEmpty()
            || txtnumerodocumento.getText().trim().isEmpty()
            || txtnombres.getText().trim().isEmpty()
            || txtapellidos.getText().trim().isEmpty()
            || txttelefono1.getText().trim().isEmpty()
            || jDatefechanacimiento.getDate() == null
            || txtdireccionactual.getText().trim().isEmpty()
            || txtcorreo1.getText().trim().isEmpty()
            || txtestado.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Complete los campos obligatorios."
        );

        return;
    }

    String sql =
            "INSERT INTO empleado ("
            + "id_tipo_documento, "
            + "id_genero, "
            + "id_profesion, "
            + "id_distrito, "
            + "numero_documento, "
            + "nombres, "
            + "apellidos, "
            + "telefono1, "
            + "telefono2, "
            + "fecha_nacimiento, "
            + "direccion_actual, "
            + "correo1, "
            + "correo2, "
            + "observaciones, "
            + "estado"
            + ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try {

        if (cn == null || cn.isClosed()) {
            cn = new Conexion_bd_Luis().conectar();
        }

        try (PreparedStatement ps =
                cn.prepareStatement(sql)) {

            ps.setInt(
                    1,
                    Integer.parseInt(
                            txtidtipodocumento
                                    .getText()
                                    .trim()
                    )
            );

            ps.setInt(
                    2,
                    Integer.parseInt(
                            txtidgenero
                                    .getText()
                                    .trim()
                    )
            );

            ps.setInt(
                    3,
                    Integer.parseInt(
                            txtidprofesion
                                    .getText()
                                    .trim()
                    )
            );

            ps.setInt(
                    4,
                    Integer.parseInt(
                            txtiddistrito
                                    .getText()
                                    .trim()
                    )
            );

            ps.setString(
                    5,
                    txtnumerodocumento
                            .getText()
                            .trim()
            );

            ps.setString(
                    6,
                    txtnombres
                            .getText()
                            .trim()
            );

            ps.setString(
                    7,
                    txtapellidos
                            .getText()
                            .trim()
            );

            ps.setString(
                    8,
                    txttelefono1
                            .getText()
                            .trim()
            );

            ps.setString(
                    9,
                    txttelefono2
                            .getText()
                            .trim()
            );

            SimpleDateFormat formato =
                    new SimpleDateFormat("yyyy-MM-dd");

            ps.setString(
                    10,
                    formato.format(
                            jDatefechanacimiento.getDate()
                    )
            );

            ps.setString(
                    11,
                    txtdireccionactual
                            .getText()
                            .trim()
            );

            ps.setString(
                    12,
                    txtcorreo1
                            .getText()
                            .trim()
            );

            ps.setString(
                    13,
                    txtcorreo2
                            .getText()
                            .trim()
            );

            ps.setString(
                    14,
                    txtobservaciones
                            .getText()
                            .trim()
            );

            ps.setString(
                    15,
                    txtestado
                            .getText()
                            .trim()
            );

            ps.executeUpdate();
        }

        JOptionPane.showMessageDialog(
                this,
                "Empleado registrado correctamente."
        );

        limpiarCampos();

        BTN_Guardar.setEnabled(false);

        cargarTabla();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Los campos de ID deben contener números."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al guardar empleado:\n"
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_GuardarActionPerformed

    private void BTN_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ModificarActionPerformed
    if (txtidempleado.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un empleado de la tabla."
        );

        return;
    }

    String sql =
            "UPDATE empleado SET "
            + "id_tipo_documento = ?, "
            + "id_genero = ?, "
            + "id_profesion = ?, "
            + "id_distrito = ?, "
            + "numero_documento = ?, "
            + "nombres = ?, "
            + "apellidos = ?, "
            + "telefono1 = ?, "
            + "telefono2 = ?, "
            + "fecha_nacimiento = ?, "
            + "direccion_actual = ?, "
            + "correo1 = ?, "
            + "correo2 = ?, "
            + "observaciones = ?, "
            + "estado = ? "
            + "WHERE id_empleado = ?";

    try {

        try (PreparedStatement ps =
                cn.prepareStatement(sql)) {

            ps.setInt(
                    1,
                    Integer.parseInt(
                            txtidtipodocumento
                                    .getText()
                                    .trim()
                    )
            );

            ps.setInt(
                    2,
                    Integer.parseInt(
                            txtidgenero
                                    .getText()
                                    .trim()
                    )
            );

            ps.setInt(
                    3,
                    Integer.parseInt(
                            txtidprofesion
                                    .getText()
                                    .trim()
                    )
            );

            ps.setInt(
                    4,
                    Integer.parseInt(
                            txtiddistrito
                                    .getText()
                                    .trim()
                    )
            );

            ps.setString(
                    5,
                    txtnumerodocumento.getText().trim()
            );

            ps.setString(
                    6,
                    txtnombres.getText().trim()
            );

            ps.setString(
                    7,
                    txtapellidos.getText().trim()
            );

            ps.setString(
                    8,
                    txttelefono1.getText().trim()
            );

            ps.setString(
                    9,
                    txttelefono2.getText().trim()
            );

            SimpleDateFormat formato =
                    new SimpleDateFormat("yyyy-MM-dd");

            ps.setString(
                    10,
                    formato.format(
                            jDatefechanacimiento.getDate()
                    )
            );

            ps.setString(
                    11,
                    txtdireccionactual.getText().trim()
            );

            ps.setString(
                    12,
                    txtcorreo1.getText().trim()
            );

            ps.setString(
                    13,
                    txtcorreo2.getText().trim()
            );

            ps.setString(
                    14,
                    txtobservaciones.getText().trim()
            );

            ps.setString(
                    15,
                    txtestado.getText().trim()
            );

            ps.setInt(
                    16,
                    Integer.parseInt(
                            txtidempleado.getText().trim()
                    )
            );

            ps.executeUpdate();
        }

        JOptionPane.showMessageDialog(
                this,
                "Empleado modificado correctamente."
        );

        limpiarCampos();

        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        cargarTabla();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Los campos de ID deben contener números."
        );

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al modificar empleado:\n"
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_BTN_ModificarActionPerformed

    private void BTN_DesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_DesactivarActionPerformed
    if (txtidempleado.getText().trim().isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Seleccione un empleado."
        );

        return;
    }

    String sql =
            "UPDATE empleado "
            + "SET estado = 'INACTIVO' "
            + "WHERE id_empleado = ?";

    try (PreparedStatement ps =
            cn.prepareStatement(sql)) {

        ps.setInt(
                1,
                Integer.parseInt(
                        txtidempleado
                                .getText()
                                .trim()
                )
        );

        ps.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Empleado dado de baja correctamente."
        );

        limpiarCampos();

        BTN_Modificar.setEnabled(false);
        BTN_Desactivar.setEnabled(false);

        cargarTabla();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Error al dar de baja:\n"
                + e.getMessage()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "El ID del empleado no es válido."
        );
    }
    }//GEN-LAST:event_BTN_DesactivarActionPerformed

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txttelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono1ActionPerformed

    private void txttelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefono1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono1KeyTyped

    private void txttelefono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefono2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono2ActionPerformed

    private void txttelefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefono2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefono2KeyTyped

    private void txtdireccionactualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionactualKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionactualKeyTyped

    private void txtcorreo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreo2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreo2KeyTyped

    private void txtobservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobservacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionesActionPerformed

    private void txtobservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobservacionesKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionesKeyTyped

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtestadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frm_Mantempleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cerrar;
    private javax.swing.JButton BTN_Desactivar;
    private javax.swing.JButton BTN_EXCEL;
    private javax.swing.JButton BTN_Guardar;
    private javax.swing.JButton BTN_Modificar;
    private javax.swing.JButton BTN_Nuevo;
    private javax.swing.JButton BTN_PDF;
    private javax.swing.JButton BTN_verempleadocapacitacion;
    private javax.swing.JTable JTABLE_Mantempleadocapacitacion;
    private javax.swing.JTextField TXT_Buscar;
    private com.toedter.calendar.JDateChooser jDatefechanacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcorreo1;
    private javax.swing.JTextField txtcorreo2;
    private javax.swing.JTextField txtdireccionactual;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtiddistrito;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtidgenero;
    private javax.swing.JTextField txtidprofesion;
    private javax.swing.JTextField txtidtipodocumento;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnumerodocumento;
    private javax.swing.JTextField txtobservaciones;
    private javax.swing.JTextField txttelefono1;
    private javax.swing.JTextField txttelefono2;
    // End of variables declaration//GEN-END:variables
}
